// Generated by routing/build-geometry.cjs from src/utils/routes.ts. Do not edit.
const earthRadiusKm = 6371;
const overlapToleranceMetres = 0.5;
const roadCellMetres = 100;
export function distanceBetween(a, b) {
    const toRad = (value) => (value * Math.PI) / 180;
    const dLat = toRad(b.latitude - a.latitude);
    const dLon = toRad(b.longitude - a.longitude);
    const lat1 = toRad(a.latitude);
    const lat2 = toRad(b.latitude);
    const h = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2;
    return earthRadiusKm * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h));
}
export function routeDistance(route) {
    return route.slice(1).reduce((total, point, index) => total + distanceBetween(route[index], point), 0);
}
export function pointAtBearing(center, distanceKm, bearingDeg) {
    const bearing = (bearingDeg * Math.PI) / 180;
    const angular = distanceKm / earthRadiusKm;
    const lat = (center.latitude * Math.PI) / 180;
    const lon = (center.longitude * Math.PI) / 180;
    const nextLat = Math.asin(Math.sin(lat) * Math.cos(angular) + Math.cos(lat) * Math.sin(angular) * Math.cos(bearing));
    const nextLon = lon + Math.atan2(Math.sin(bearing) * Math.sin(angular) * Math.cos(lat), Math.cos(angular) - Math.sin(lat) * Math.sin(nextLat));
    return { latitude: (nextLat * 180) / Math.PI, longitude: (nextLon * 180) / Math.PI };
}
export function decodePolyline(encoded, precision = 6) {
    const coordinates = [];
    const factor = 10 ** precision;
    let index = 0;
    let latitude = 0;
    let longitude = 0;
    const component = () => {
        let result = 0;
        for (let shift = 0; shift <= 30 && index < encoded.length; shift += 5) {
            const byte = encoded.charCodeAt(index++) - 63;
            if (byte < 0 || byte > 63 || (shift === 30 && byte > 3))
                return null;
            result |= (byte & 0x1f) << shift;
            if (byte < 32)
                return result & 1 ? ~(result >>> 1) : result >>> 1;
        }
        return null;
    };
    while (index < encoded.length) {
        const latDelta = component(), lonDelta = component();
        if (latDelta === null || lonDelta === null)
            return [];
        latitude += latDelta;
        longitude += lonDelta;
        coordinates.push({ latitude: latitude / factor, longitude: longitude / factor });
    }
    return coordinates;
}
export function roadCells(segment) {
    const dx = segment.end.x - segment.start.x;
    const dy = segment.end.y - segment.start.y;
    const steps = Math.max(1, Math.ceil(Math.max(Math.abs(dx), Math.abs(dy)) / roadCellMetres));
    const cells = [];
    for (let i = 0; i <= steps; i++) {
        const cell = [
            Math.floor((segment.start.x + dx * i / steps) / roadCellMetres),
            Math.floor((segment.start.y + dy * i / steps) / roadCellMetres),
        ];
        const last = cells[cells.length - 1];
        if (!last || last[0] !== cell[0] || last[1] !== cell[1])
            cells.push(cell);
    }
    return cells;
}
export function sharedRoadInterval(current, previous) {
    const ux = (current.end.x - current.start.x) / current.length;
    const uy = (current.end.y - current.start.y) / current.length;
    const vx = (previous.end.x - previous.start.x) / previous.length;
    const vy = (previous.end.y - previous.start.y) / previous.length;
    // A crossing is not road reuse. Allow only near-collinear overlap, in either direction.
    if (Math.abs(ux * vy - uy * vx) > 0.01)
        return null;
    const ax = previous.start.x - current.start.x;
    const ay = previous.start.y - current.start.y;
    const bx = previous.end.x - current.start.x;
    const by = previous.end.y - current.start.y;
    const from = ax * ux + ay * uy;
    const to = bx * ux + by * uy;
    const start = Math.max(0, Math.min(from, to));
    const end = Math.min(current.length, Math.max(from, to));
    if (end - start <= 0.01)
        return null;
    const offsetStart = ax * -uy + ay * ux;
    const offsetEnd = bx * -uy + by * ux;
    const offsetAt = (distance) => offsetStart + (offsetEnd - offsetStart) * (distance - from) / (to - from);
    if (Math.abs(offsetAt(start)) > overlapToleranceMetres || Math.abs(offsetAt(end)) > overlapToleranceMetres)
        return null;
    return [start, end];
}
export function repeatedRoadRatio(route) {
    if (route.length < 2)
        return 0;
    const origin = route[0];
    const metresPerDegree = earthRadiusKm * 1000 * Math.PI / 180;
    const longitudeScale = Math.cos(origin.latitude * Math.PI / 180);
    const points = route.map((point) => ({
        x: (point.longitude - origin.longitude) * metresPerDegree * longitudeScale,
        y: (point.latitude - origin.latitude) * metresPerDegree,
    }));
    const cells = new Map();
    const segments = [];
    let total = 0;
    let repeated = 0;
    for (let i = 1; i < points.length; i++) {
        const start = points[i - 1];
        const end = points[i];
        const length = Math.hypot(end.x - start.x, end.y - start.y);
        if (length <= 0.01)
            continue;
        const segment = { start, end, length };
        const occupied = roadCells(segment);
        const candidates = new Set();
        for (const [x, y] of occupied) {
            for (let dx = -1; dx <= 1; dx++)
                for (let dy = -1; dy <= 1; dy++) {
                    for (const index of cells.get(`${x + dx},${y + dy}`) ?? [])
                        candidates.add(index);
                }
        }
        const overlaps = [...candidates].map((index) => sharedRoadInterval(segment, segments[index]))
            .filter((interval) => interval !== null).sort((a, b) => a[0] - b[0]);
        let coveredUntil = 0;
        for (const [from, to] of overlaps) {
            repeated += Math.max(0, to - Math.max(from, coveredUntil));
            coveredUntil = Math.max(coveredUntil, to);
        }
        total += length;
        const index = segments.push(segment) - 1;
        for (const [x, y] of occupied) {
            const key = `${x},${y}`;
            const bucket = cells.get(key);
            if (bucket)
                bucket.push(index);
            else
                cells.set(key, [index]);
        }
    }
    return total ? repeated / total : 0;
}
export function splitSharedAccess(route) {
    let left = 0, right = route.length - 1;
    let outward = route[0], inward = route[right];
    let accessKm = 0;
    const interpolate = (a, b, fraction) => ({
        latitude: a.latitude + (b.latitude - a.latitude) * fraction,
        longitude: a.longitude + (b.longitude - a.longitude) * fraction,
    });
    while (left + 1 < right && distanceBetween(outward, inward) <= 0.0005) {
        const outKm = distanceBetween(outward, route[left + 1]);
        const inKm = distanceBetween(inward, route[right - 1]);
        if (outKm < 0.00001) {
            outward = route[++left];
            continue;
        }
        if (inKm < 0.00001) {
            inward = route[--right];
            continue;
        }
        const step = Math.min(outKm, inKm);
        const nextOut = interpolate(outward, route[left + 1], step / outKm);
        const nextIn = interpolate(inward, route[right - 1], step / inKm);
        if (distanceBetween(nextOut, nextIn) > 0.0005)
            break;
        accessKm += step;
        outward = nextOut;
        inward = nextIn;
        if (outKm <= inKm)
            outward = route[++left];
        if (inKm <= outKm)
            inward = route[--right];
    }
    if (!accessKm)
        return { accessKm: 0, outbound: [], loop: route, returning: [], withoutReturn: route };
    const outbound = route.slice(0, left + 1);
    if (distanceBetween(outbound[outbound.length - 1], outward) > 0.00000001)
        outbound.push(outward);
    const returning = route.slice(right);
    if (distanceBetween(inward, returning[0]) > 0.00000001)
        returning.unshift(inward);
    return {
        accessKm,
        outbound,
        loop: [outward, ...route.slice(left + 1, right), inward],
        returning,
        // Keep the outbound access: this also detects a loop that reuses it again.
        withoutReturn: [...route.slice(0, right), inward],
    };
}
export function roundTripRoadUse(route) {
    const split = splitSharedAccess(route);
    const remainingRepeatedRatio = repeatedRoadRatio(split.withoutReturn);
    const limitKm = Math.min(0.5, routeDistance(route) * 0.05);
    return {
        valid: route.length > 2 && split.accessKm <= limitKm && remainingRepeatedRatio === 0,
        sharedAccessKm: split.accessKm,
        remainingRepeatedRatio,
    };
}
